/*
 * This source file was generated by the Gradle 'init' task
 */
package io.landotech;

import com.sshtools.common.publickey.SshKeyPairGenerator;
import com.sshtools.common.ssh.SshException;
import com.sshtools.common.ssh.components.SshKeyPair;
import com.sshtools.common.ssh.components.SshPublicKey;
import com.sshtools.common.ssh.components.SshPrivateKey;
import com.sshtools.common.publickey.OpenSSHPrivateKeyFile;
import com.sshtools.common.publickey.OpenSSHPublicKeyFile;

/*
 * ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIC8tpQkKOU8fBAJIVO60VWLWA5g1XLG+QV0eQQkWhl8+ aaron@devbox
 *
 * */

import java.io.IOException;


public class App {

    public static void main(String[] args) {
        SshKeyPair keyPair = generateKeyPair();
        if (keyPair == null) {
            System.err.println("Failed to generate ssh key pair");
        } else {
            SshPublicKey publicKey = keyPair.getPublicKey();
            SshPrivateKey privateKey = keyPair.getPrivateKey();
            System.out.println("Private key: " + privateKey.getAlgorithm());
            System.out.println("Public key: " + publicKey.getAlgorithm());
        }
    }

    public static SshKeyPair generateKeyPair() {
        try {

            return SshKeyPairGenerator.generateKeyPair(SshKeyPairGenerator.ED25519);
        } catch (IOException | SshException io) {
            System.out.println("Failed to generate key pair: " + io.getMessage());
        }
        return null;
    }
}
